[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sentinel-q"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "apscheduler",
    "fastapi",
    "httpx",
    "uvicorn[standard]",
    "python-dotenv",
    "pydantic-settings",
    "loguru",
    "sqlalchemy",
    "psycopg2-binary",
    "passlib[bcrypt]",
    "python-jose[cryptography]",
    "slowapi",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-asyncio",
    "anyio",
]

[tool.setuptools.packages.find]
where = ["src"]
